[pytest]
pythonpath = .
testpaths = tests
addopts = -ra -vv --tb=short --cov=src --cov-fail-under=95 --cov-report=term-missing --cov-report=html
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:numpy.ufunc size changed, may indicate binary incompatibility\.:RuntimeWarning
    ignore:Converting `np\.inexact` or `np\.floating` to a dtype is deprecated\..*:DeprecationWarning
    ignore:.*L-BFGS-B solver are deprecated.*:DeprecationWarning
norecursedirs = venv .git node_modules __pycache__ .hypothesis
